 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
/root/projects/reptilia/env/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
movistar
/root/projects/reptilia/env/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/root/projects/reptilia/env/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
 * Serving Flask app "app" (lazy loading)
 * Environment: development
 * Debug mode: on
movistar
/root/projects/reptilia/env/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/root/projects/reptilia/app/routes/auth.py", line 75, in validate
    name = request.json.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_socketio/__init__.py", line 45, in __call__
    return super(_SocketIOMiddleware, self).__call__(environ,
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/engineio/middleware.py", line 74, in __call__
    return self.wsgi_app(environ, start_response)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/projects/reptilia/env/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 108, in wrapper
    return fn(*args, **kwargs)
  File "/root/projects/reptilia/app/routes/auth.py", line 75, in validate
    name = request.json.get('name')
AttributeError: 'NoneType' object has no attribute 'get'
12572
Terminado para: {'host': '172.16.30.10', 'user': 'root', 'password': 'hdec123', 'db': 'marcador'}
Terminado para: {'host': '172.16.30.11', 'user': 'root', 'password': 'hdec123', 'db': 'marcador'}
Terminado para: {'host': '172.16.30.12', 'user': 'root', 'password': 'hdec123', 'db': 'marcador'}
Terminado para: {'host': '172.16.30.13', 'user': 'root', 'password': 'hdec123', 'db': 'marcador'}
Terminado para: {'host': '172.16.30.14', 'user': 'root', 'password': 'hdec123', 'db': 'marcador'}
/root/projects/reptilia/env/lib/python3.8/site-packages/pandas/compat/__init__.py:120: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
